name: tpeo_new_fellow
description: A UT-only marketplace app (Campus Connect) â€” minimal scaffold for auth + Firestore
publish_to: none
version: 0.1.0
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.0
  flutter_riverpod: ^2.3.0
  go_router: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
